### ISSUE TITLE
[Feature Request] Persistent sideload files folder

### ISSUE THREAD

**Issue by vinorodrigues** [vial-kb/vial-gui#101]
I would be so awesome to have a dedicated folder that one can drop "that other too" `.json` files into.  And then when Vial starts up or detects a KB can do it's thing... but then also look inside that folder for keymap defs.

Copy once, and then never needing to sideload each and every time.

.....bliss

**Comment by xyzz** [comment]
Please submit feature requests at https://feedback.vial.today/
