### ISSUE TITLE
Space key not shown in VIAL UI for Keychron sideloaded JSONs

### ISSUE THREAD

**Issue by CrazyCoder** [vial-kb/vial-gui#105]
Sample JSONs:

https://cdn.shopify.com/s/files/1/0059/0630/1017/files/q1_us_ansi_non_knob_ver1.08.json.zip?v=1650248055
https://cdn.shopify.com/s/files/1/0059/0630/1017/files/q2_us_ansi_non_knob_ver1.04.json.zip?v=1650248870

These JSON files are linked from the following pages:

https://www.keychron.com/blogs/archived/how-to-reset-your-keychron-q1-to-factory-settings
https://www.keychron.com/blogs/archived/how-to-factory-reset-or-flash-your-qmk-via-enabled-keychron-q2-keyboard

VIAL does not display the Space button in the UI:

<img width="788" alt="chrome_2022-05-28_12-47-41" src="https://user-images.githubusercontent.com/122834/170840780-76f56c4e-fb8d-430f-b756-c1352548c747.png">

VIA works fine:

<img width="989" alt="chrome_2022-05-28_12-50-33" src="https://user-images.githubusercontent.com/122834/170840849-1a4a08c1-e436-472e-b723-29119adb58ac.png">

**Comment by xyzz** [comment]
It's a bug in keychron's json:
![image](https://user-images.githubusercontent.com/1065521/170842755-74f72278-b741-43b4-a38c-add5a772b27c.png)
The key location should be a top left legend, not the center one. It's mentioned in VIA docs as well <https://www.caniusevia.com/docs/layouts#switch-matrix-co-ordinates>

It's currently not a goal to be bug-compatible with VIA so there's no plans fixing it.

**Comment by CrazyCoder** [comment]
Thanks for the pointer, I've managed to fix the JSON to display the Space key.
