### ISSUE TITLE
Add a support for Swap-Hands Keycodes

### ISSUE THREAD

**Issue by surfinzap** [vial-kb/vial-gui#107]
When I write any of [Swap-Hands Keycodes](https://github.com/qmk/qmk_firmware/blob/master/docs/feature_swap_hands.md) via Vial interface, I end up with the following error:
![image](https://user-images.githubusercontent.com/1387798/172540251-07148574-616b-4415-a657-adcef532589e.png)

Please, add a support for Swap-Hands Keycodes

**Comment by xyzz** [comment]
Please submit feature requests at https://feedback.vial.today/
