### ISSUE TITLE
Suggestion: Add list of PCBs or keyboards that support full feature set

### ISSUE THREAD

**Issue by verydanny** [vial-kb/vial-gui#110]
I have no idea if VIAL has a Discord, and I didn't really know who to contact, but my issue was when I was porting my DZ60RGB V2 to VIAL, I had to sacrifice quite a few features in order to get into the 32KB flash memory constraint.

My `rules.mk`:

```make
VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_EMABLE = no
SWAP_HANDS_ENABLE = no
RGB_MATRIX_ENABLE = no
```

My `config.h`:

```c
// This is for larger EEPROM for more macros
#define DYNAMIC_KEYMAP_LAYER_COUNT 3
```

After lots of search, I found that the HS60 V3 with the `STM32F303CC` has 256KB of flash memory, and would definitely work with all those features.

Maybe I'm missing something, but I'd like a list of PCBs or keyboards that have at least 64KB of flash memory. 

Maybe I should be removing some other features from the DZ60RGB V2, for example, can I remove the LUFA bootloader and just use the `.hex` old method?

**Comment by xyzz** [comment]
Please submit feature request to https://feedback.vial.today/

Our discord is linked to from https://get.vial.today/, the link is https://discord.gg/zNKEUXTKwF
