### ISSUE TITLE
[3w6] "No devices detected" – Is 3w6 supported?

### ISSUE THREAD

**Issue by pawelkontek** [vial-kb/vial-gui#114]
Is 3w6 supported? I am getting "No devices detected" while having my 3w6 connected.
I'm on MacOS 12.2.1. Macbook Pro 14.

**Comment by xyzz** [comment]
I don't see a `vial` keymap for that keyboard in our vial-qmk repo; it's still possible there is a port out there - you should contact your keyboard vendor to inquiry regarding a vial-compatible firmware.

**Comment by pawelkontek** [comment]
@xyzz that's an open source keyboard: https://github.com/weteor/3W6
