### ISSUE TITLE
Strange error messages

### ISSUE THREAD

**Issue by kannthus** [vial-kb/vial-gui#125]
Afternoon folks,

I recently tried to run Vial instead of VIA for my Keychron Q1V2, upon trying to load the VIA JSON (as the board is not recognizer otherwise) I get these errors:

![image](https://user-images.githubusercontent.com/32248891/185478090-2b039703-51e3-443b-a821-fb5deff33352.png)
(Which isn't correct as I made certain I am using the newest version of Vial)

And also
![image](https://user-images.githubusercontent.com/32248891/185478150-9c6cd7bf-5590-4210-811a-c967d02fb22f.png)
which I can't make heads or tails of.

Any help would be appreciated.

**Comment by xyzz** [comment]
The firmware is likely built from the development branch of qmk, this is not supported. That said, once qmk_firmware merges development branch into the main branch, and during the next cycle vial-qmk picks up these changes, the support will be added.
