### ISSUE TITLE
RGB is reset if the keyboard is unplugged.

### ISSUE THREAD

**Issue by trashcatt** [vial-kb/vial-gui#126]
I've noticed that RGB values get reset if the keyboard is unplugged and then plugged back in. I'm not sure if this is intended or not as I don't remember having this issue in the past. 

Currently affecting my Sneakbox M4 and my Milktruck. 
If I remember correctly it didn't affect my Murphpad, but again, I could be wrong. 

EDIT: Never mind. I saw the issue in the vial-gmk repo.

**Comment by l4u** [comment]
related to https://github.com/vial-kb/vial-qmk/issues/213
