### ISSUE TITLE
macOS App not showing Record macro or delay action

### ISSUE THREAD

**Issue by thienmdang** [vial-kb/vial-gui#130]
Using zoom65 keyboard and;
Side loading .json file: https://drive.google.com/file/d/1ccM6jrPUvhoygvPGaZ1i4bYQ0juRxKYa/

Once side loading .json file, the keyboard appears, but when attempting to create macro, there is no record macro button or delay action in the app.

**Comment by xyzz** [comment]
Macro recording currently is not supported on macOS. If you're interested in this feature, I suggest submitting a suggestion at https://feedback.vial.today/
