### ISSUE TITLE
adding Tri_Layer_State support

### ISSUE THREAD

**Issue by doesntfazer** [vial-kb/vial-gui#144]
I feel like since this is an integral part of a lot of peoples keymaps it should be something that can be toggled in the QMK settings page. 

I would like to mention you can activate it when you compile the firmware. But if you wanted to turn it off for any particular reason, there is no way to do this. 

For more information on how "tri_layer_state" works, Please see this documentation.
https://docs.splitkb.com/hc/en-us/articles/360018614379-Using-tri-state-layers

**Comment by xyzz** [comment]
Please submit feature requests to https://feedback.vial.today/
