### ISSUE TITLE
Add a list of recent layouts

### ISSUE THREAD

**Issue by mitchcurtis** [vial-kb/vial-gui#150]
This would make it so much easier to quickly switch layouts before e.g. playing a game. I would add it myself but https://github.com/vial-kb/vial-gui/issues/121 prevents me from contributing to this project.

**Comment by xyzz** [comment]
Please use https://feedback.vial.today/ for feature requests.

That said - I suggest using layers instead with a hotkey assigned to TG(x); changing layout very often would negatively impact your flash/eeprom lifetime.

**Comment by mitchcurtis** [comment]
Oh, good to know. Is there any further info you could link to about flash/eeprom lifetime?

**Comment by mitchcurtis** [comment]
Created https://feedback.vial.today/suggestions/351549/add-a-list-of-recent-layouts.
