### ISSUE TITLE
[Windows] Main window isn't initialized when it is closed on a monitor that no longer exists.

### ISSUE THREAD

**Issue by thompson-vii** [vial-kb/vial-gui#175]
Windows 10 22H
On closing the program the position of the window is registered on 
`Computer\HKEY_CURRENT_USER\SOFTWARE\Vial\Vial`

When the program window is closed on a second monitor that is later disconnected the program window fails to initialize. 

To Reproduce
![image](https://user-images.githubusercontent.com/31672176/232865672-435c991b-26b5-4204-b6f5-36c136598dc1.png)

In the registry of vial change pos to values outside of all currently connected monitor.

**Comment by xyzz** [comment]
This should be fixed by #181
