### ISSUE TITLE
AttributeError: 'Keyboard' object has no attribute 'tap_dance_count'

### ISSUE THREAD

**Issue by ArnaudPeler** [vial-kb/vial-gui#182]
Hello! I have a Keychron K9 Pro and would like to configure it using vial-gui on Linux, but I can't import the .json file for this keyboard because of this error: 'AttributeError: `Keyboard' object has no attribute 'tap_dance_count'`

What should I do ? (I prefer not installing chrome just for using VIA)

**Comment by xyzz** [comment]
sounds like it's currently running VIA firmware so your options are either to install Vial firmware on the keyboard, or use the VIA app with the existing firmware
