### ISSUE TITLE
Won't detect the kbd craft keyboard 

### ISSUE THREAD

**Issue by lSc0rpzx** [vial-kb/vial-gui#187]
Restarted everything still won't detect it

**Comment by TweetyDaBird** [comment]
There are known issues with KBD craft keyboards and their firmware. Unfortunately they are so far unwilling to supply the firmware as source code, so the userbase of Vial and it's developers are unable to provide that much help. 

I strongly suggest you make yourself a right pest to them, and get them to fix the issue, and preferably even cough up the source code. Note that this is a very unofficial stance, and my personal opinion, so please take it for what it is.

**Comment by xyzz** [comment]
Not an issue with the gui
