### ISSUE TITLE
VIal V0.7 - Unable to load dummy JSON

### ISSUE THREAD

**Issue by farhandsome** [vial-kb/vial-gui#188]
The newest iteration of VIAL is unable to load dummy JSONs for testing/porting. Below is the error code given: 

![image](https://github.com/vial-kb/vial-gui/assets/73175556/cf1b17ea-944b-49bb-9899-6e83414ff575)

**Comment by Glodigit** [comment]
I'm also getting the same error.

**Comment by xyzz** [comment]
Fixed in c704b49ccdfb8b50b019fadc6be30a466b767fa9
