### ISSUE TITLE
User defined custom keycode limited to 16

### ISSUE THREAD

**Issue by Alectardy98** [vial-kb/vial-gui#189]
When trying to make more then 16 custom keycodes, using QK_KB_0, the GUI will not open and gives an error like shown in vial 0.7
![](https://cdn.discordapp.com/attachments/798171620577509377/1131707254698164366/Screenshot_2023-07-20_at_6.00.15_PM.png)

**Comment by Alectardy98** [comment]
this can be fixed by changing the limits defined in src/main/python/keycodes/keycodes_v6.py at line 578

**Comment by Alectardy98** [comment]
![Screenshot 2023-07-20 at 10 00 27 PM](https://github.com/vial-kb/vial-gui/assets/61422584/5b89b6ac-5b71-4dfa-afd3-2525307d695e)
 
 please make this change, it will solve a lot of my issues. Here is a photo of it working currently i have tested with it set to 50

**Comment by xyzz** [comment]
Fixed in 64e725971ed7ba143cf188f5985e6e3eed776c3e

**Comment by Alectardy98** [comment]
thank you, when will this be pushed into release?

**Comment by Alectardy98** [comment]
![Screenshot 2024-04-11 at 5 00 27 PM](https://github.com/vial-kb/vial-gui/assets/61422584/2fcf671c-a287-4171-9e24-45d1188f1c2c)

Has the fix been implemented yet?
