### ISSUE TITLE
Lighting Controls for Underglow (edit : and Backlight) Not Working

### ISSUE THREAD

**Issue by a33bis** [vial-kb/vial-gui#192]
In the process of adding back support for the infinity87 rev1 standard ([vial-qmk#514](https://github.com/vial-kb/vial-qmk/pull/514)) that was removed in the last merge I realized it is not possible to control the underglow from the "Lighting" tab anymore.

By default the underglow of the board is set to solid red with max brightness but by default the tab displays "All Off", 0 brightness and black. I can select different effects but it does nothing, I can click and choose a different color but right after clicking "Ok" it stays on black, and lastly I can not interact at all with the brightness slider.
![image](https://github.com/vial-kb/vial-gui/assets/48868985/8c27c2fc-3a28-4593-b959-922e31d2e0f2)
Firmware is fine I believe since, it was working fine in my initial port 3 months ago and using the RGB control keycodes works right now (the "Lighting" tab  stays however as described)

**Comment by a33bis** [comment]
Tested with a different pcb (Galatea Rev2) same issue.

**Comment by a33bis** [comment]
Backlight controls also do not work, I can interact with the slider unlike with underglow but it has no effect, must use keycodes.

**Comment by xyzz** [comment]
Fixed in https://github.com/vial-kb/vial-qmk/commit/ca3a3d8030f2d3395e84efcc64ac943e99ca9fbc
