### ISSUE TITLE
[BUG]Vial automatically generates LT keycodes that exceed the upper limit if the keyboard has more than 16 layers.

### ISSUE THREAD

**Issue by zhaqian12** [vial-kb/vial-gui#195]
Vial automatically generates LT keycodes that exceed the upper limit if the keyboard has more than 16 layers, it will result in a runtime error.
```    
for x in range(layers):
        KEYCODES_LAYERS.append(Keycode("LT{}(kc)".format(x), "LT {}\n(kc)".format(x),
                                       "kc on tap, switch to layer {} while held".format(x), masked=True))
```
Maybe we can put a limit on it, thank you.

**Comment by xyzz** [comment]
Fixed in https://github.com/vial-kb/vial-gui/commit/caf6c60543616628ba1f7995e8aad6fd64fe5beb
