### ISSUE TITLE
Add docs URL to description

### ISSUE THREAD

**Issue by winslet** [vial-kb/vial-gui#2]
**Maintainer required:**
The docs URL should be added to the description of this repository along with the one line about the project.

> Vial is an open-source cross-platform (Windows, Linux and Mac) GUI and a QMK fork for configuring your keyboard in real time, similar to VIA.

> vial-kb.github.io

![image](https://user-images.githubusercontent.com/13980028/103645673-4d6e8a00-4f50-11eb-89d4-8f17ebfda22c.png)

![image](https://user-images.githubusercontent.com/13980028/103645223-9540e180-4f4f-11eb-8788-6eb818de9d97.png)

**Comment by xyzz** [comment]
sure thing
