### ISSUE TITLE
How can I obtain the detailed documentation for the communication protocol between the host computer and the keyboard firmware? 

### ISSUE THREAD

**Issue by liangtian123** [vial-kb/vial-gui#202]
VIAL is awesome! I would like to develop a Flutter or web-based GUI client based on VIAL. However, I couldn't find the documentation for the communication protocol between the GUI client and the keyboard. For example, what is the data format for sending key remapping commands, and is it sent via HID? I have limited knowledge of PyQt5 and cannot understand the VIAL-GUI code in detail.

Any help would be greatly appreciated!

Let me reiterate my question: For instance, if I want to achieve key remapping through a Flutter application, let's say I want to remap the A key to the B key, what kind of data should I send to the keyboard firmware? Is it sent via HID? What are the corresponding data formats for other operations?

**Comment by xyzz** [comment]
Currently there's no protocol documentation, you'll have to refer to the source code.
