### ISSUE TITLE
[Request] Support for Apple Silicon Macs

### ISSUE THREAD

**Issue by fzhwenzhou** [vial-kb/vial-gui#213]
Currently, the binary distribution of Vial only supports Intel Silicon Macs. Although it can still run on Apple Silicon Macs via Rosetta 2, it also needs to support Apple Silicon Macs natively since Resetta 2 is becoming a deprecated feature. Because this project is written in Python, I don't think it will be a technical issue. Thank you!

**Comment by xyzz** [comment]
Please use https://feedback.vial.today/ for feature requests

**Comment by peterjc** [comment]
Logged as https://feedback.vial.today/suggestions/617497/include-apple-silion-arm-cpu-binaries-in-releases-m1-m2-m3-m4
