### ISSUE TITLE
Download VIA definitions does nothing (Linux)

### ISSUE THREAD

**Issue by tudorjnu** [vial-kb/vial-gui#224]
Clicking the "Download VIA Definitions" does nothing. I am trying to figure out if it wrote something in a temp file. This is also happening on Windows, see  https://github.com/vial-kb/vial-gui/issues/83 .

**Comment by tudorjnu** [comment]
Update: Found it under `.cache/Vial/via_keyboards.json`. Leaving it here for others to reference :)

**Comment by xyzz** [comment]
as mentioned in the linked issue, there is no UI indication of successful completion, but it does work
