### ISSUE TITLE
newer version or protocol of vial gui not able to read or configure keyboard layout. 

### ISSUE THREAD

**Issue by CameronWeller** [vial-kb/vial-gui#226]
there is an associated error window output, pasted below. And a device that was compiled a long time ago on an older firmware version ~mid 2021 was able to be configured and the matrix tested on the same version of the GUI. 

the newer compiled keyboard is unable to work with older versions of the vial GUI, I get an error specifying a protocol change. 

File "main_window.py", line 279, in on_devices_updated   File "main_window.py", line 283, in on_device_selected   File "autorefresh\autorefresh.py", line 79, in select_device   File "vial_device.py", line 51, in open   File "protocol\keyboard_comm.py", line 79, in reload   File "protocol\keyboard_comm.py", line 153, in reload_layout  TypeError: list indices must be integers or slices, not str

**Comment by xyzz** [comment]
> the newer compiled keyboard is unable to work with older versions of the vial GUI, I get an error specifying a protocol change.

You need to use the newest available version of Vial, there is no goal of forwards compatibility (only backwards compatibility)

**Comment by CameronWeller** [comment]
> > the newer compiled keyboard is unable to work with older versions of the vial GUI, I get an error specifying a protocol change.
> 
> You need to use the newest available version of Vial, there is no goal of forwards compatibility (only backwards compatibility)
I am not saying that was the issue. Just wanted to specify that I tried ;(

**Comment by xyzz** [comment]
If you get a protocol version error with the latest version of Vial, then it means you're trying to use it with a VIA keyboard which is no longer supported. You should be either 1) using the VIA application with that keyboard, or 2) flash the Vial firmware on the keyboard following manufacturers instructions

**Comment by CameronWeller** [comment]
(Before I continue I just want to say I appreciate your help and effort making this project)

But yeah this is a custom keyboard that wrote the config for and am flashing myself. I only ever intended to use this keyboard project of mine with vial support, I have not built any via support into the project except what was necessary for getting vial up and running.
