### ISSUE TITLE
Feature request: Test Matrix feature

### ISSUE THREAD

**Issue by Pieterv24** [vial-kb/vial-gui#23]
One of the things I currently miss in the GUI, is the ability to test whether keys work and are pressed correctly acoarding to the matrix

**Comment by xyzz** [comment]
Actually I've removed that functionality from vial-qmk because it's essentially a keylogger. So it's not possible to implement a matrix test, it is however possible to implement a basic keycode test.

**Comment by Pieterv24** [comment]
would it be possible to reintruduce it, behind the security keys feature?
It was something I thought was quite handy.
I'm unsure how it was implemented in QMK in the first place though

**Comment by Nisker** [comment]
> I'm unsure how it was implemented in QMK in the first place though
> 
I think it can be reimplemented in your firmware (vial-qmk) by commenting out or deleteing the "goto skip;" on line 260 in "quantum/via.c". 
Then recompile and flash your kb and use VIA to test matrix and vial for everything else.
_disclaimer: I haven't tested it, and might be wrong_

Do note it brings back the security risk, that a malicious program could monitor your keys in the background.

**Comment by xyzz** [comment]
Merged the PR, thanks for contributing
