### ISSUE TITLE
There is a problem with LM(layer, mod) 

### ISSUE THREAD

**Issue by ada19911201** [vial-kb/vial-gui#235]
#define LM(layer, mod) (QK_LAYER_MOD | (((layer)&0xF) << 5) | ((mod)&0x1F)) in qmk，but vial gui is def LM(layer, mod): return (r("QK_LAYER_MOD") | (((layer)&0xF) << 4) | ((mod)&0xF))

**Comment by genics** [comment]
the same problem there.

**Comment by xyzz** [comment]
a76a79dfc3b2a82e9fe9ca44100005650097a469
