### ISSUE TITLE
Russian layout Linux

### ISSUE THREAD

**Issue by JostBrand** [vial-kb/vial-gui#241]
Hi, I woud like to know which linux keymap corresponds to the one displayed in vial. The regular ru keymap does not fit as it does not have the keys with alt modifier and others I have found have slightly other symbols.

**Comment by xyzz** [comment]
Hello, which keys do you mean by alt modifier? To my knowledge, Alt isn't used in the ЙЦУКЕН layout. Regarding the layout on Linux, it should be the default one you get with `setxkbmap -layout us,ru`

**Comment by xyzz** [comment]
No response, closing

**Comment by JostBrand** [comment]
Sorry for not reporting back.

My friend told me it was ru sun type 6.
