### ISSUE TITLE
[UI/UX] Cannot easily move one layer forward or backward

### ISSUE THREAD

**Issue by 0dminnimda** [vial-kb/vial-gui#252]
Since the layer number is important in ordering of keys and KC_TRNS I want to be able to move a free unused layer between existing ones and add some overrrides. But it's not possible inside of the app. The only way I've found to this without painstakingly copying each of the layers one number forward is to open the .vil as json and cut and paste ...

**Comment by xyzz** [comment]
Please use https://feedback.vial.today/ for feature requests
