### ISSUE TITLE
Can you control rgb lights like via？

### ISSUE THREAD

**Issue by monkeychou** [vial-kb/vial-gui#32]
<img width="1392" alt="截屏2021-05-23 下午7 00 19" src="https://user-images.githubusercontent.com/63698796/119257822-9ff7cc80-bbf9-11eb-8b3f-7b5ba09584c8.png">
like this

**Comment by xyzz** [comment]
yes it is already implemented and will be available in the next release (0.3), for now you can download an automated build from https://github.com/vial-kb/vial-gui/actions/runs/869003683 to test this functionality & report any issues
