### ISSUE TITLE
MOD Tap config behaviour is inconsistent

### ISSUE THREAD

**Issue by dreipunkteinsvier** [vial-kb/vial-gui#41]
When configuring mod tap keys in the gui, settings are only saved if the complete key is selected.
See attached screen shots for differance.

Works:
![works](https://user-images.githubusercontent.com/87331570/127213234-9cb36cbd-181c-4f9b-b19d-c037f9eea2ff.png)

Doesn't work:
![doesntwork](https://user-images.githubusercontent.com/87331570/127213309-a547c9b6-3989-40ee-8ba0-a2bcfcad906f.png)

**Comment by xyzz** [comment]
Fixed in f51b6d4c73f33d2986352324746b25b2dd58006e
