### ISSUE TITLE
The Tap Dance tab is empty

### ISSUE THREAD

**Issue by georgezhe** [vial-kb/vial-gui#44]
I'm on macOS Catalina 10.15.7 and when I open vial for my Melody65 keyboard, it detects the keyboard successfully, but the tap dance tab is empty.

**Comment by Tubo** [comment]
Same on KDE Neon with AppImage.

**Comment by xyzz** [comment]
While there's a bug here (the empty tab should be hidden altogether), it's probably not the fix you want. If you're looking for tap dance support in vial gui, you must be running latest vial-qmk firmware (not via firmware).

**Comment by Tubo** [comment]
That solved it. For future reference, I followed the 'porting guide' and installed the vial-qmk firmware. Now there are many more options showing up, including the tap/hold-related options. Awesome!

**Comment by xyzz** [comment]
Fixed by 8db625e3804dd2460b4ecc06ad6d01a6ff153eff
