### ISSUE TITLE
Some Keycodes are missing/forbidden in the GUI

### ISSUE THREAD

**Issue by Technofrikus** [vial-kb/vial-gui#45]
Hello,

the following keycodes are missing/not allowed in the GUI. When entering the hex it works (tested for the VOLUP).

- KC__VOLUP
- KC___VOLDOWN
- LSG(kc)
- All Audio keycodes (did not test all but several): https://beta.docs.qmk.fm/using-qmk/hardware-features/feature_audio#audio-keycodes
- Haptic Feedback keycodes https://beta.docs.qmk.fm/using-qmk/hardware-features/feature_haptic_feedback#haptic-keycodes

Maybe more are missing, but these were the ones I encountered.

For me it would be ok to just allow them via the any-function for the obscure ones like audio and haptics. The others would be great to also have in the GUI.

Thanks!

**Comment by xyzz** [comment]
> KC__VOLUP, KC___VOLDOWN

Both added, though don't do anything on my windows pc at least.

> LSG(kc)

This is available as "SGUI", though I've added LSG and LSG_T aliases.

> All Audio keycodes (did not test all but several)

All added.

> Haptic Feedback keycodes

All added.
