### ISSUE TITLE
Firmware not saving to keyboard

### ISSUE THREAD

**Issue by swizzley** [vial-kb/vial-gui#47]
Keymap is stored or cached, but power cycle reverts it back to QMK. 

Keyboard is GMMK Pro ANSI, not tested on any others. 

Weird thing is, I flashed to QMK, then to VIA, before flashing to VIAL, but never remapped anything in VIA, and it obviously didn't have any of my keymaps from QMK. The weird thing is that after unplugging on the VIAL firmware, it reverts back to my QMK keymap, which was overwritten by the default VIA keymap.

**Comment by xyzz** [comment]
You should contain Glorious support about that, Vial team does not provide support for keyboard-specific issues.
