### ISSUE TITLE
Tap dance waits for input even when there is no double tap set

### ISSUE THREAD

**Issue by dlip** [vial-kb/vial-gui#50]
When i single-tap tap dance with no double tap set, i would like it to output the character instantly rather than waiting 500 ms

![image](https://user-images.githubusercontent.com/283316/135976186-41585657-cbf0-4b6f-ab8c-a6f4e1bb4cb0.png)

**Comment by xyzz** [comment]
It's not possible with qmk's tap dance implementation (as it doesn't send key release events to our handlers), might have to think of a workaround for this.

**Comment by xyzz** [comment]
Try this branch for now https://github.com/vial-kb/vial-qmk/tree/tap-dance-release and let me know if it fixes the issue

**Comment by dlip** [comment]
You are amazing, works great!

**Comment by dlip** [comment]
@xyzz are you ok to merge this?
