### ISSUE TITLE
Add option to save and load macros from file

### ISSUE THREAD

**Issue by noah-kiser-rea** [vial-kb/vial-gui#54]
I have often had the need to transfer a macro to another board, or duplicate a macro to have 2 different but similar macros.
Copying manually is tedious at best, and aggravating at worst.

An option to save the current macro, or load a macro from file would be nice. I'll take a crack at implementing it this weekend.

**Comment by NCKiser** [comment]
Pull request associated:

#55 Issue #54 save load macro from file
