### ISSUE TITLE
Tap dance configuration tabs are missing

### ISSUE THREAD

**Issue by trackballenjoyer** [vial-kb/vial-gui#56]
I'm new to VIA and Vial, so this could totally have something to do with my keyboard the sideloaded layout I'm using. I'm not sure, but the tap dance configuration tabs are missing where the documentation indicates they would be:

### From the docs
![image](https://user-images.githubusercontent.com/94089111/141220175-a55747d0-bc18-461a-9055-0a7e3f9c2780.png)

### What I see
<img width="917" alt="image" src="https://user-images.githubusercontent.com/94089111/141218778-770147c1-3966-49dd-b60e-ccfb2daf26b6.png">

### Details
Operating system: macOS Monterey 12.0.1
Vial version: 0.4.1

**Comment by NCKiser** [comment]
Do you have Tap Dance enabled on the keyboard's firmware? If the keyboard is running VIA firmware, Tap Dance is not currently configurable with the Vial GUI.

**Comment by trackballenjoyer** [comment]
Tap Dance and VIA are both enabled for my firmware. I assumed I would need both for Vial to work and for Tap Dance to be configurable with it.

The documentation seems to suggest that Tap Dance *is* configurable with Vial: https://get.vial.today/manual/tap-dance.html#tap-dance. Is this not fully implemented yet?

**Comment by NCKiser** [comment]
It is configurable with Vial, when the keyboard is running Vial firmware. Your keyboard is running VIA firmware.

You can port from VIA to Vial by following the porting guide here:
https://get.vial.today/docs/porting-to-vial.html

**Comment by trackballenjoyer** [comment]
Gotcha. I assumed Vial functioned more as an alternative frontend for VIA with some additional configuration options. I didn't realize that it required different firmware, but that makes sense.

Thanks!
