### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by ricrug** [vial-kb/vial-gui#60]
> ERROR: Could not find a version that satisfies the requirement sip==4.19.8 (from versions: 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.2.0, 5.3.0, 5.4.0, 5.5.0, 6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.1.0, 6.1.1, 6.2.0, 6.3.0, 6.3.1, 6.4.0, 6.5.0)
ERROR: No matching distribution found for sip==4.19.8

How can I get around this problem?

**Comment by xyzz** [comment]
you have to use python 3.6 as this is the latest version `fbs` supports
