### ISSUE TITLE
Window size not stored

### ISSUE THREAD

**Issue by Technofrikus** [vial-kb/vial-gui#62]
Hello,

as poligone mentioned in the Discord:
https://discord.com/channels/798171334756401183/798171873951219754/922494119643840543

The window size is reset every time the app is restarted. This means frequent resizing of the window, so all keys can be seen for mapping them.

Would be great if:
- the window size would be stored and restored
- the window would automatically resized to show all available keys in the lower half

I think he is running a PC, I am running it on a Mac with the same problem.

**Comment by xyzz** [comment]
fixed in 452917905a8d3a3d520740c2a87e3ef2b586cdd6
