### ISSUE TITLE
fbs run,fbs freeze  ISSUE,Please teach me God

### ISSUE THREAD

**Issue by latincompass** [vial-kb/vial-gui#72]
Sir,When i CMD RUN fbs run,fbs freezejust like this picture,do not have MENU,can you tell me the Problem?
https://github.com/latincompass/2-RotaryEncoder-pad/blob/master/fbs%20run.jpg

**Comment by xyzz** [comment]
You're running `fbs run` from `src/main/python` directory:
![image](https://user-images.githubusercontent.com/1065521/151094455-53c178d7-9f32-4efd-823e-373d129fac2f.png)

however, you should be running from the root directory (i.e. `C:\vial-gui-main`).
