### ISSUE TITLE
 how to use tap_dance

### ISSUE THREAD

**Issue by monkeychou** [vial-kb/vial-gui#77]
TAP_DANCE_ENABLE = yes   in  rules.mk
#define TAPPING_TERM      175          in       config.h
but errors

Linking: .build/choupad_via.elf                                                                     [ERRORS]
 |
 | /usr/local/opt/avr-binutils/bin/avr-ld: .build/obj_choupad_via/quantum/process_keycode/process_tap_dance.o: in function `process_tap_dance_action_on_reset':
 | /Users/chou/desktop/vial/vial-qmk/quantum/process_keycode/process_tap_dance.c:99: undefined reference to `tap_dance_actions'
 | /usr/local/opt/avr-binutils/bin/avr-ld: /Users/chou/desktop/vial/vial-qmk/quantum/process_keycode/process_tap_dance.c:99: undefined reference to `tap_dance_actions'
 | /usr/local/opt/avr-binutils/bin/avr-ld: .build/obj_choupad_via/quantum/process_keycode/process_tap_dance.o: in function `_process_tap_dance_action_fn':
 | /Users/chou/desktop/vial/vial-qmk/quantum/process_keycode/process_tap_dance.c:83: undefined reference to `tap_dance_actions'
 | /usr/local/opt/avr-binutils/bin/avr-ld: /Users/chou/desktop/vial/vial-qmk/quantum/process_keycode/process_tap_dance.c:83: undefined reference to `tap_dance_actions'
 | /usr/local/opt/avr-binutils/bin/avr-ld: .build/obj_choupad_via/quantum/process_keycode/process_tap_dance.o: in function `process_tap_dance_action_on_reset':
 | /Users/chou/desktop/vial/vial-qmk/quantum/process_keycode/process_tap_dance.c:100: undefined reference to `tap_dance_actions'
 | /usr/local/opt/avr-binutils/bin/avr-ld: .build/obj_choupad_via/quantum/process_keycode/process_tap_dance.o:/Users/chou/desktop/vial/vial-qmk/quantum/process_keycode/process_tap_dance.c:100: more undefined references to `tap_dance_actions' follow
 | collect2: error: ld returned 1 exit status
 |

**Comment by xyzz** [comment]
Can you post a link to the repository with this keyboard and full configuration for it?

**Comment by monkeychou** [comment]
> 您可以使用此键盘和完整配置发布到存储库的链接吗？

https://github.com/monkeychou/choupad
thanks

**Comment by xyzz** [comment]
Following these commands:

```
git clone https://github.com/monkeychou/choupad.git
git clone https://github.com/vial-kb/vial-qmk.git
mv choupad/choupad vial-qmk/keyboards
cd vial-qmk
python3 -m venv venv
. venv/bin/activate
pip install qmk
make git-submodule
make choupad:via
```

I get the following error:

```
Compiling: keyboards/choupad/keymaps/via/keymap.c                                                  keyboards/choupad/keymaps/via/keymap.c:62:6: error: conflicting types for 'encoder_update_user'; have 'void(uint8_t,  _Bool)' {aka 'void(unsigned char,  _Bool)'}
   62 | void encoder_update_user(uint8_t index, bool clockwise) {
```

It looks your copy of vial-qmk is out of date.

After resolving the error, the firmware links successfully however it is too large:

```
Linking: .build/choupad_via.elf                                                                     [OK]
Creating load file for flashing: .build/choupad_via.hex                                             [OK]
Copying choupad_via.hex to qmk_firmware folder                                                      [OK]
Checking file size of choupad_via.hex                                                              
 * The firmware is too large! 34758/28672 (6086 bytes over)
 [ERRORS]

make[1]: *** [tmk_core/rules.mk:490: check-size] Error 1
Make finished with errors
make: *** [Makefile:478: choupad:via] Error 1
```

Therefore, it looks like your vial-qmk is not fully updated, and there is no issue here.
