### ISSUE TITLE
Vial GUI just not opening. 

### ISSUE THREAD

**Issue by PapaZ810** [vial-kb/vial-gui#80]
I double click on the executable and the program runs, but the GUI does not pop up at all. No window shows up for the program. I am running Windows 11, which I suspect to be the problem.

**Comment by whoisjoshua** [comment]
I have the same problem and I'm on Windows 10. Vial was running for me a while ago until I updated. Now it doesn't work any longer.

**Comment by claudiobottari** [comment]
Same here, was it fixed?

**Comment by xyzz** [comment]
should have been fixed by 960060a9fc53e8a20a55e92fba797099d68c4dba in 0.7
