### ISSUE TITLE
Mouse key settings missing from QMK settings in v0,4.2. Feature regression?

### ISSUE THREAD

**Issue by ujl123** [vial-kb/vial-gui#84]
https://get.vial.today/changelog/release-0.4.html#mouse-keys

The docs lists the mouse-keys settings but with the newest version, I do not  see this option anywhere. My version also doesn't  include the "Firmware updater". Both the windows  installer version and the windows portable v.0,4,2 don't have it.

![image](https://user-images.githubusercontent.com/13132548/159843679-26f0f6cc-c195-4d33-b25f-880ef904c289.png)

**Comment by xyzz** [comment]
Mouse keys tab missing indicates the firmware was compiled without qmk mousekey support.

Firmware updater tab is missing because that's only included for keyboards utilizing the [vibl](https://github.com/vial-kb/vibl) protocol, which gmmk pro isn't using.

**Comment by ujl123** [comment]
> Mouse keys tab missing indicates the firmware was compiled without qmk mousekey support.
> 
> Firmware updater tab is missing because that's only included for keyboards utilizing the [vibl](https://github.com/vial-kb/vibl) protocol, which gmmk pro isn't using.

Thank you for the confirmation!
