### ISSUE TITLE
Keypad Equals Not Always Available

### ISSUE THREAD

**Issue by bgkendall** [vial-kb/vial-gui#85]
When the Vial key selector is in full-size keyboard layout, the `KC_KP_EQUAL` key is not available.
When the layout is TKL, or smaller, it is available with the other number pad keys.

`KC_KP_COMMA` is the same, although I don’t personally care about that one! :)

**Comment by xyzz** [comment]
that should be fixed with https://github.com/vial-kb/vial-gui/commit/00a4c2a6c9bd98c48c49246b5d9f512e50508cab

![image](https://user-images.githubusercontent.com/1065521/162130219-0d1515f6-9015-4209-8923-49df9e4ea4e6.png)
