### ISSUE TITLE
my keyboard with three encoder has error

### ISSUE THREAD

**Issue by WatsonJay** [vial-kb/vial-gui#88]
my keyboard have three encoder, I use \n\n\n\n\n\n\n\n\ne to defined, but I got this error
![image](https://user-images.githubusercontent.com/26869453/162694595-a747c253-667a-404e-90fd-88fed9098fe6.png)
my json like this
`{
    "name": "editorMarcos",
    "keyboard_name": "editorMarcos",
    "maintainer": "WatsonJay",
    "vendorId": "0xFEED",
    "productId": "0x6062",
    "lighting": "qmk_rgblight",
    "matrix": { "rows": 5, "cols": 5 },
    "layouts": {
        "keymap": [
            {"name":"via"},
            [{"x": 0.5},"0,0",{  "x": 1},"0,1"],
            ["4,0\n\n\n\n\n\n\n\n\ne","4,1\n\n\n\n\n\n\n\n\ne","4,2\n\n\n\n\n\n\n\n\ne","4,3\n\n\n\n\n\n\n\n\ne"],
            [{"x": 0.5},"1,0",{"x": 1},"1,1",{"x": 0.5},"0,2","0,3"],
            [{"x": 0.5},"2,0",{"x": 1},"2,1",{"x": 0.5},"1,2","1,3","1,4"],
            [{"x": 1.5},"3,1",{"x": 1.5},"2,2","2,3","2,4"],
            [{"x": 1},"3,0\n\n\n\n\n\n\n\n\ne","0,4\n\n\n\n\n\n\n\n\ne",{"x": 1},"3,2","3,3","3,4"]
          ]
    }
}`

**Comment by SrGuspin** [comment]
did you solve this? If it is the case, please tell me how :(
