### ISSUE TITLE
How to convert vil to a qmk valid json

### ISSUE THREAD

**Issue by mmngreco** [vial-kb/vial-gui#90]
Hi there!

I found this project so useful. It was very easy to change the keyboard layout using this gui. However, I need to change some variables in the `config.h`, so to do that I thought in converting my `vil` file into `json` and then into `keyboard.c` using `qmk` to avoid re-implement all the layers again.

There's a way to achieve this? or a better approach?

**Comment by xyzz** [comment]
Please use our [discord](https://discord.gg/zNKEUXTKwF) for questions, and the issue tracker for bug reports related to vial. But the short answer is that it's not something that's implemented.
